version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.2
    branches:
      only:
        - circleci
    steps:
      - add_ssh_keys:
          fingerprints:
            - "64:f5:f6:57:a0:6a:84:20:59:fe:3e:ef:8a:cc:82:5f"
      - checkout
      - run:
          name: Setup environment
          command: make venv
      - run:
          name: Build schema
          command: make build-all
      - run:
          name: Deploy new schema
          command: make deploy
