version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.2
    branches:
      only:
        - circleci
    steps:
      - checkout
      # Download and cache dependencies
#      - restore_cache:
#          keys:
#          - v1-dependencies-{{ checksum "requirements.txt" }}
#          # fallback to using the latest cache if no exact match is found
#          - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            git clone https://github.com/jburianek/openapi2jsonschema.git
            python3 -m venv venv
            . venv/bin/activate
            pip install -e openapi2jsonschema
#      - save_cache:
#          paths:
#            - ./venv
#          key: v1-dependencies-{{ checksum "requirements.txt" }}
      - run:
          name: Build schema
          command: openapi2jsonschema -o "v1.13.0-standalone-strict" --kubernetes --stand-alone --strict https://raw.githubusercontent.com/kubernetes/kubernetes/v1.13.0/api/openapi-spec/swagger.json
      - store_artifacts:
          path: v1.13.0-standalone-strict
          destination: v1.13.0-standalone-strict
