version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.2
    branches:
      only:
        - circleci
    steps:
      - checkout
      - run:
          name: Setup environment
          command: make venv
      - run:
          name: Build schema
          command: make v1.13.1
      - store_artifacts:
          path: output
          destination: output
